Updating prod flow

diff --git a/.github/workflows/deploy-metabase-production.yml b/.github/workflows/deploy-metabase-production.yml
--- a/.github/workflows/deploy-metabase-production.yml
+++ b/.github/workflows/deploy-metabase-production.yml
@@ -20,8 +20,8 @@ jobs:
       # - name: Run Import Script
       #   if: success()
       #   env:
-      #     API_KEY: ${{ secrets.STAGING_API_KEY }}
-      #     ENDPOINT_URL: ${{ vars.STAGING_ENDPOINT_URL }}
+      #     API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
+      #     ENDPOINT_URL: ${{ vars.PRODUCTION_ENDPOINT_URL }}
       #   run: |
       #     echo "Running Import Script..."
       #     echo "Endpoint URL: $ENDPOINT_URL"
@@ -29,3 +29,53 @@ jobs:
       #     go run main.go import \
       #       endpoint_url=$ENDPOINT_URL \
       #       api_key=$API_KEY
+
+      - name: Get Dashboard ID from Entity ID
+        id: get_dashboard_id
+        if: success()
+        env:
+          API_KEY: ${{ secrets.STAGING_API_KEY }}
+          ENDPOINT_URL: ${{ vars.STAGING_ENDPOINT_URL }}
+          ENTITY_ID: ${{ vars.ENTITY_ID }}
+        run: |
+          echo "Getting entity ID from dashboard..."
+          ENTITY_ID=$(go run main.go get_dashboard_id \
+            endpoint_url=$ENDPOINT_URL \
+            api_key=$API_KEY \
+            entity_id=$ENTITY_ID | grep DASHBOARD_ID | cut -d'=' -f2)
+          echo "DASHBOARD_ID=$DASHBOARD_ID" >> $GITHUB_ENV
+
+      - name: Cleaning Repository variable entity_id
+        if: success()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          echo "Updating repository variable with entity ID..."
+          curl -X PATCH \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/variables/ENTITY_ID" \
+            -d "{\"value\":\" "}"
+      
+      - name: Call Dashboard Update Endpoint
+        id: call_dashboard_update
+        if: success()
+        env:
+          DASHBOARD_ID: ${{ env.DASHBOARD_ID }}
+          ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
+          MANAGER_API_URL: ${{ vars.MANAGER_API_PROD_URL }}
+        run: |
+          echo "Calling dashboard update endpoint for dashboard ID: $DASHBOARD_ID"
+          curl --location --request PUT "$MANAGER_API_URL/es/api/v3/toggle/feature/user/dashboard" \
+            --header "x-api-key: $ADMIN_API_KEY" \
+            --header 'Content-Type: application/json' \
+            --data "{
+                \"name\": \"Update dashboard $DASHBOARD_ID\",
+                \"id_dashboard\": $DASHBOARD_ID
+              }"
+          
+          # Check if the curl command succeeded
+          if [ $? -ne 0 ]; then
+            echo "Failed to call dashboard update endpoint"
+            exit 1
+          fi
